name: E2E Test App
on:
  push:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run app
        run: python3 ./src/app/app.py &
      - name: Test GET-request
        run: |
          ANSW=$(curl http://127.0.0.1:5000/)
          if [ "$ANSW" != "Hello, World!" ]; then
          exit 1
          else
          echo "Test PASS"
          fi
