name: Slave Workflow

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Start"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Slave Workflow"

