name: Staging

on:
  push:
    branches: 
      - main
  workflow_dispatch:
#   workflows: ["E2E Test App"]
#   types:
#     - completed

jobs:
  containering:
    runs-on: ubuntu-latest

    steps:
      - run: echo "DONE"
