name: Welcome workflow
run-name: Welcome new commits
on:
  push:
    branches:
      - main
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello new commits"
      - run: echo "Hello new commits"
